export const UNAUTHORIZED = "UNAUTHORIZED";
export const REQUIRED = "REQUIRED";
export const NOT_FOUND = "NOT_FOUND";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const ALREADY_VERIFIED = "ALREADY_VERIFIED";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const VERIFIED = "VERIFIED";
export const RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS";
export const TOKEN_MISSING = "TOKEN_MISSING";
export const USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
export const ANSWER_NOT_MATCHING = "ANSWER_NOT_MATCHING";
export const PASSWORDS_ARE_SAME = "PASSWORDS_ARE_SAME";
export const PASSWORDS_ARE_NOT_SAME = "PASSWORDS_ARE_NOT_SAME";
export const SECTION_COUNT_EXCEEDS = "SECTION_COUNT_EXCEEDS";
export const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
export const VALIDATION_FAILED = "VALIDATION_FAILED";
export const CREATION_FAILED = "CREATION_FAILED";

export const MAX_TEAM_ERROR = "MAX_TEAM_ERROR";
export const MAX_TEAM_COUNT = 5;

export const MAX_MEMBER_ERROR = "MAX_MEMBER_ERROR";
export const MAX_MEMBER_COUNT = 50;

export const MAX_PROJECTS_ERROR = "MAX_PROJECTS_ERROR";
export const MAX_PROJECTS_COUNT = 3;

export const MAX_BOARDS_ERROR = "MAX_BOARDS_ERROR";
export const MAX_BOARDS_COUNT = 20;

export const VERIFY_TOKEN_EXPIRY = "2d";
export const JOIN_TOKEN_EXPIRY = "2d";
